Removed powershell v6
pragnagopa/azure-functions-supported-runtime-stacks pull request #15
Opened 2020-08-06 21:12 UTC by gzuber

According to https://github.com/Azure/azure-cli/issues/14649, powershell v6 is approaching end of life and should be removed.

2020-08-06 21:27 UTC, pragnagopa commented
stack should not be removed. Instead set isDeprecated to true.

2020-08-06 21:29 UTC, pragnagopa commented
@Francisco-Gamino - Please use https://github.com/Azure/azure-functions-ux/pull/5201/files as an example and send update to official stacks

cc @ammanifold as FYI

2020-08-06 21:34 UTC, Francisco-Gamino commented
@gzuber : Do you still need to make a code change? Or setting `isDeprecated` to `true` will block the creation of the PowerShell 6.2 function app?

2020-08-06 21:37 UTC, pragnagopa requested changes
Please update the PR

2020-08-06 21:44 UTC, ammanifold commented
I thought we didn't want to update this until we have official GA for PS7

2020-08-06 21:45 UTC, gzuber commented
> @gzuber : Do you still need to make a code change? Or setting `isDeprecated` to `true` will block the creation of the PowerShell 6.2 function app in the Az CLI?

@Francisco-Gamino yeah this will still require a code change. Even if the CLI had support for isDeprecated, I'd still have to update the stacks API file (right now we just include the json in the CLI build). But I have support for isHidden and isPreview so it shouldn't be difficult to add.

2020-08-06 21:51 UTC, pragnagopa commented
Thanks @gzuber - changes LGTM

@Francisco-Gamino  - can you ACK on @ammanifold question above :

> I thought we didn't want to update this until we have official GA for PS7 ?

2020-08-06 21:54 UTC, Francisco-Gamino commented
> I thought we didn't want to update this until we have official GA for PS7
@stefanushinardi could you please help answer @ammanifold question?

2020-08-06 23:22 UTC, stefanushinardi commented
@ammanifold is right, we should wait to release this until PS7 GA announcement. If this commit gets merged today, when would be it be released?

2020-08-06 23:31 UTC, pragnagopa commented
@stefanushinardi thanks for the input

>  If this commit gets merged today, when would be it be released?

To avoid coordinating multiple release schedules across multiple repos, let's wait on updating stacks. We should update the stacks after PS7 GA annoucement. Do you have an ETA?

2020-08-06 23:36 UTC, stefanushinardi commented
@pragnagopa  ETA that we are currently tracking is 3rd week of August

2020-08-07 00:08 UTC, pragnagopa commented
@gzuber / @Francisco-Gamino  - Since the changes required in the tooling are small, lets hold off on merging these changes.

Please add support for `isDeprecated` flag. Once this change is merged, only work remaining would be to update stacks in tooling repos.

2020-08-07 00:11 UTC, Francisco-Gamino commented
> @gzuber / @Francisco-Gamino - Since the changes required in the tooling are small, lets hold off on merging these changes.

> Please add support for isDeprecated flag. Once this change is merged, only work remaining would be to update stacks in tooling repos.

Sounds good. Thanks @pragnagopa .

2020-08-11 17:53 UTC, stefanushinardi commented
@pragnagopa @gzuber @Francisco-Gamino, the PS7 GA announcement of  is now live: https://azure.microsoft.com/en-us/updates/azure-functions-powershell-7-support-is-now-generally-available/. Please merge this with the next release. Thanks!

2020-08-11 17:59 UTC, pragnagopa approved these changes

2020-08-11 17:59 UTC, merged

2020-08-11 18:00 UTC, pragnagopa commented
@Francisco-Gamino - please send a PR updating stacks in Ux repo.

2020-08-11 18:15 UTC, Francisco-Gamino commented
> @Francisco-Gamino - please send a PR updating stacks in Ux repo.

@pragnagopa  - will do and tag you in the PR.

2020-08-11 19:06 UTC, Francisco-Gamino commented
Here is the link to the UX PR: https://github.com/Azure/azure-functions-ux/pull/5230