Adding PowerShell 7.0 and Java 11 to Windows and Linux stack definitions
pragnagopa/azure-functions-supported-runtime-stacks pull request #2
Opened 2020-05-30 02:54 UTC by Francisco-Gamino

This PR contains the following:

* Adding Java 11 and PowerShell 7.0 to Windows functions stack
* Adding Java 11 to Linux functions stack.
* Renaming PowerShell 6 to PowerShell 6.2 for consistency. Please note that the current version of PowerShell is 7.0, and the next version will be 7.1 with .Net 5

2020-05-30 06:23 UTC, Francisco-Gamino commented
cc: @amamounelsayed

2020-06-09 14:34 UTC, pragnagopa requested changes
We should not display minor version unless we guarantee continued support. For example, we display full version for python: `3.6` and `3.7` - users are pinning to a specific version. For Node, we display `10`, `8`, `12` as the minor version is upgraded by us without notice. Same applies for Java.

2020-06-09 14:35 UTC, pragnagopa commented
Can you please start an email with Ux once these changes are merged? Thanks!

2020-06-09 14:38 UTC, pragnagopa commented
@shimedh / @ehamai -  We need to update stacks to include Java 11 and Powershell 7.  Do let us know if we can send a PR to update the contents for the stacks stores in Ux.

2020-06-09 16:12 UTC, pragnagopa commented
cc @anatolib

2020-06-09 16:34 UTC, AnatoliB commented
> We should not display minor version unless we guarantee continued support. For example, we display full version for python: `3.6` and `3.7` - users are pinning to a specific version. For Node, we display `10`, `8`, `12` as the minor version is upgraded by us without notice. Same applies for Java.

@pragnagopa The reason we are adding the minor version number for PowerShell is exactly that: we learned that PowerShell can introduce breaking changes without incrementing the major version. Specifically, PowerShell 7.1 is going to be the case. So, we will not be upgrading the minor version for our customers automatically, with or without notice. When we add 7.1, we'll have to keep 7.0, so the minor version is important, at least within 7.

For PowerShell 6, it is less important because no new version beyond 6.2 is ever expected, so we are doing this for consistency only.

2020-06-09 16:43 UTC, pragnagopa commented
If we are not upgrading minor versions, placeholder logic that calculates  placeholder id needs to be updated. Is there a planned work item for this?

2020-06-09 16:43 UTC, amamounelsayed commented
cc @anirudhgarg

2020-06-09 16:51 UTC, AnatoliB commented
> If we are not upgrading minor versions, placeholder logic that calculates placeholder id needs to be updated. Is there a planned work item for this?

Yes, I'm aware of this. There is no existing work item yet because the upgrade to 7.1 is expected around the end of this year, so nothing is planned yet and we have enough time to update the placeholder logic. In the meantime, we know that this upgrade will _eventually_ happen, and exposing "7.1" next to "7" in the UX will be awkward.

2020-06-09 17:05 UTC, pragnagopa commented
> There is no existing work item yet because the upgrade to 7.1 is expected around the end of this year, so nothing is planned yet and we have enough time to update the placeholder logic.

As the changes need to part of Antares and release schedules could span over months, can you please open a work item for this as part Antares work items?  It is important to open a workitem and mention it here for tracking purposes.  This would also require us to think about which versions will be supported for placeholders.

2020-06-09 17:05 UTC, pragnagopa approved these changes

2020-06-09 17:05 UTC, pragnagopa commented
Merging this PR.

2020-06-09 17:05 UTC, merged

2020-06-09 18:12 UTC, ehamai commented
@ammanifold and @shimedh for FYI...

2020-06-11 02:06 UTC, ammanifold commented
> @ammanifold and @shimedh for FYI...

Files two tracking items:
Task 7416328: [Stacks][Function App][Ibiza Create Stacks] Update Power 7.0 and Java 11
Task 7416332: [Stacks][Function App][2020-05-01] Update PowerShell 7.0 and Java 11